[package]
name = "rsfer"
version = "0.1.0"
edition = "2021"
authors="gosha"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo-aur="1.5.0"